version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: stop_server
      timeout: 30
      runas: root
  ApplicationStart:
    - location: applicationStart.sh   
      timeout: 15
      runas: root
